[package]
name = "my_project"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
noise = "0.9.0"
rand = "0.9.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true